version: "3.9"
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Bek@rys_2003
      - POSTGRES_DB=assignment_3
      - POSTGRES_HOST=postgres
    ports:
      - 5432:5432
    volumes:
      - //c/Program Files/PostgreSQL/14/data
    networks:
      - my-network
    
networks:
  my-network:
    external: true