version: '3.9'
services:
    project: 
      build: ./
      ports:
        - "8080:8080"
      command: /app/main
      environment:
        - DB_URL=db:5432
      networks:
        - my-network
networks:
  my-network:
    external: true

