version: "3.9"
services:
  postgres:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=Bek@rys_2003
      - DB_NAME=assignment_3
    ports:
      - 5436:5432
  project: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on: 
      - postgres
    entrypoint: ["/app/wait-for-it.sh", "postgres:5432", "--"]
    command: ["/app/main"]